### PR TITLE
Backend updates

### PR DESCRIPTION
**Pull request by jgriffiths**
This is PR #186 plus some after the fact cleanup.

I have verified that receive addresses generated with an amount present change the qrcode as they are entered, and that copying the address results in a correct bitcoin: URI in the clipboard.

It would be nice additionally if the send tab could handle a bitcoin: URI being pasted into the address field. Nonetheless this should be fine to merge now IMO.

### CODE REVIEW

**Comment by zidagar** [comment]
I've see possible crash onStart when try to call mAmountFields.setIsPausing(...) with mAmountFields null
I think we need to add a check to mAmountFields

**Comment by jgriffiths** [comment]
@zidagar I will add some checks for null for now, thanks for reporting.

We have some GaService/WalletClient work to do around recent backend changes which will be fairly intrusive but should fix the current crashes that are seen on startup/restore(*). Once those changes are in I would like to revisit this code.

Specifically I think eventually we want:
- The UI item member variables to be held in the AmountFields only, and not also duplicated in the holding Fragment.
- The pausing determination to be made by the holding Fragment and not by using mIsPausing in the AmountFields class. Getting the state handling correct for the main fragment holder was a pretty big/complicated task and it would be good to avoid keeping this state elsewhere.

(*) The upcoming changes will make post login processing atomic so that all user data required for view construction is available before any views are created. Currently post login processing is async which causes issues when certain post login calls take too long.

**Comment by zidagar** [comment]
@jgriffiths wonderful for the merge and thw crashes on startup!
However, I've wrote the AmountFields class on the basis of your logic / code because i do not know every workaround / possible problem in the current code.
Anyway, your fixes and considerations are ok! Thank you for your clarifications :-)

**Comment by jgriffiths** [comment]
Thanks @zidagar, Lawrence and I are very happy to see your contributions too, keep 'em coming!

**Comment by zidagar** [comment]
@jgriffiths when do you think to release the fixes about the crashes on startup/restore?

**Comment by jgriffiths** [comment]
@zidagar This set of patches requires back end changes which are still under development. I think GA testnet should have them within a week, and I hope the GreenBits changes will be done in that time also. I don't know how long after that we will update the production mainnet instance, but I think another week seems likely. So I would hope 2 weeks or less.

You can track the progress of my changes on https://github.com/jgriffiths/GreenBits/tree/segwit_updates. I may split out parts of this work that can be merged as separate PRs as in the case of PR 188 and 189.

**Comment by zidagar** [comment]
Wonderful, I understood the problems. Thank you @jgriffiths for the quickly reply!

**Pull request merged**
